name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.24.6
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test
      - name: Run tests with coverage
        run: go test -covermode=atomic -coverprofile=coverage.out ./...
